Support for Red V3.1 (discord.py 1.0.1) (#7)
* [datautils] update for v3.1

* [messageslog] update for v3.1

* [minecraftdata] update for v3.1

* [personalroles] update for v3.1

* [minecraftdata] black style

* [personalroles] change get_user_info to fetch_user

* [leveler] update for V3.1

* [leveler] fix ValueError

ValueError: embedded null byte

* [leveler] seek 0 position of BytesIO

* [minecraftdata] clear formatting in players list
use server's host and port instead of user's input

* [minecraftdata] refactor code

* [steamcommunity] refactor code

* [steamcommunity] check for incorrect steamid32

* [datautils] add banner field to serverinfo
[steamcommunity] update locales

* [messageslog] makes [p]ignore one cmd, instead of group of commands

* [messageslog] black code formatting

some aliases for main command

* [leveler] update info.json

* [minecraftdata] optimise converter
optimise exception handling

* [smmdata] new cog

* [smmdata] rename ru_RU translation file

* [smmdata] update ru-RU translation

* [smmdata] fix exception when no one is cleared the level

* update README.md

* [smmdata] fixes exception when level doesn't have difficulty yet

* [smmdata] fixes another exception when level doesn't have difficulty yet

* [smmdata] return float instead of None

* [smmdata] refactor code

add icon and level's tag to embed

* [smmdata] do not show footer text, if no tag set